services:
  # proxy:
  #   build: ./proxy
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - WEB=web:8080
  #   restart: always
  #   networks:
  #     - internal
  #     - external
  web:
    build: ./web
    environment:
      - DSN=mysql://root:changeme@db/ctf
    restart: always
    depends_on:
      - db
    networks:
      - external
      - internal
    ports:
      - 8080:8080
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    networks:
      - internal

networks:
  internal:
    internal: true
  external:
